version: '3'

services:
  nodejs:
    build: .
    image: paulorcvieira/ubuntu-sshd-nvm:latest
    volumes:
      - .:/workspace
    ports:
      - "22"
      - "3030:3030"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432"
    volumes:
      - ./crud-node-postgres/database:/var/lib/postgresql/data